[package]
name = "bufstream"
version = "0.1.3"
authors = ["The Rust Project Developers"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/bufstream"
homepage = "https://github.com/alexcrichton/bufstream"
documentation = "http://alexcrichton.com/bufstream"
description = """
Buffered I/O for streams where each read/write half is separately buffered
"""

[dependencies.futures]
optional = true
version = "0.1.13"

[dependencies.tokio-io]
optional = true
version = "0.1.1"

[features]
default = []
tokio = ["futures", "tokio-io"]
